spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${SPRING_ROOT_URL}
    username: ${SPRING_ROOT_USERNAME}
    password: ${SPRING_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: m.mucahitbayar@gmail.com
    password: Fb05435446158
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      protocol: smtp
      test-connection: false

ownable:
  app:
    jwt:
      secret: ownableSecretKey
      expiration-ms: 86400000
