spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${SPRING_ROOT_URL}
    username: ${SPRING_ROOT_USERNAME}
    password: ${SPRING_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

ownable:
  app:
    jwt:
      secret: ownableSecretKey
      expiration-ms: 86400000